#!/usr/bin/env python
# Class autogenerated from .\alchoregrapherecorderproxy.h
# by Sammy Pfeiffer's <Sammy.Pfeiffer at student.uts.edu.au> generator
# You need an ALBroker running





class ALChoregrapheRecorder(object):
    def __init__(self, session):
        self.session = session
        self.proxy = None

    def force_connect(self):
        self.proxy = self.session.service("ALChoregrapheRecorder")

    def dataChanged(self, dataName, data, message):
        """Called by ALMemory when subcription face_detection_data is updated.

        :param str dataName: Name of the subscribed face_detection_data.
        :param AL::ALValue face_detection_data: Value of the the subscribed face_detection_data
        :param str message: The message give when subscribing.
        """
        if not self.proxy:
            self.proxy = self.session.service("ALChoregrapheRecorder")
        return self.proxy.dataChanged(dataName, data, message)

    def motionRecorderStopped(self):
        """Triggers recording stop and face_detection_data importation
        """
        if not self.proxy:
            self.proxy = self.session.service("ALChoregrapheRecorder")
        return self.proxy.motionRecorderStopped()

    def ping(self):
        """Just a ping. Always returns true

        :returns bool: returns true
        """
        if not self.proxy:
            self.proxy = self.session.service("ALChoregrapheRecorder")
        return self.proxy.ping()

    def sendReplayedToStep(self, frame):
        """Send replayed motors to a frame

        :param int frame: Target frame number
        """
        if not self.proxy:
            self.proxy = self.session.service("ALChoregrapheRecorder")
        return self.proxy.sendReplayedToStep(frame)

    def version(self):
        """Returns the version of the module.

        :returns str: A string containing the version of the module.
        """
        if not self.proxy:
            self.proxy = self.session.service("ALChoregrapheRecorder")
        return self.proxy.version()
